[package]
name = "blog_os"
version = "0.1.0"
edition = "2021"
build = "build.rs"  # Add this line

[dependencies]
spin = "0.9.8"
volatile = "0.4.6"
riscv = "0.10.1"
bitflags = "2.4.1"
uart_16550 = "0.3.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
