[build]
target = "riscv64gc-unknown-none-elf"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -cpu rv64 -nographic -kernel"

rustflags = [
    "-C", "link-arg=-Tkernel.ld",
    "-C", "link-arg=-n",
    "-C", "force-frame-pointers=yes",
    "-C", "relocation-model=static"
]
